#!/bin/bash
#Installimg the sotawhat(axiv daily) for the Linux based global installation.
echo 'Installing required packages for Arxiv_updates---------'
echo '-------------------------------------------------------'
bash -c "sudo pip3 install -r /usr/bin/requirements.txt"
python3 /usr/bin/requirements.py

