Document: arxivupdates
Title: Debian arxivupdates Manual
Author: <insert document author here>
Abstract: This manual describes what arxivupdates is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/arxivupdates/arxivupdates.sgml.gz

Format: postscript
Files: /usr/share/doc/arxivupdates/arxivupdates.ps.gz

Format: text
Files: /usr/share/doc/arxivupdates/arxivupdates.text.gz

Format: HTML
Index: /usr/share/doc/arxivupdates/html/index.html
Files: /usr/share/doc/arxivupdates/html/*.html
