#!/bin/sh
# preinst script for arxivupdates
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
    echo 'Installing required packages for Arxiv_updates---------'
    echo '-------------------------------------------------------'
    bash -c "sudo pip3 install PyEnchant"
    bash -c "sudo pip3 install nltk" 
    bash -c "sudo python /usr/bin/requirements.py"
    python - << EOF
    import nltk
    nltk.download('punkt')
EOF
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
