#!/bin/bash
#Installimg the sotawhat(axiv daily) for the Linux based global installation.
echo 'Installing required packages for Arxiv_updates---------'
echo '-------------------------------------------------------'
bash -c "sudo pip3 install -r requirements.txt"
python3 requirements.py
